[tools]
clojure = "1.12.0"
java = "temurin-21.0.6+7.0.LTS"

[tasks.format]
run = "clojure -M:format"

[tasks.test]
run = "clojure -M:test:repl"

[tasks.antq]
raw = true
run = "clojure -M:antq"

[tasks.repl]
raw = true
run = "clojure -X:test:repl giants-shoulders.repl/start!"

[tasks.release]
run = "clojure -M:release"
depends_post = ["format-pom"]

[tasks.format-pom]
run = "xmllint --format pom.xml --output pom.xml"
